spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amigoscodedemo
    data-username: root
    data-password: Welcome@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
  profiles:
    active: dev
server:
  port: 8081